# Generated by Django 4.0.5 on 2022-10-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('unit_price', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('purchase_date', models.DateField()),
            ],
        ),
    ]
