# Generated by Django 4.0.5 on 2022-10-29 06:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
