# Generated by Django 4.0.5 on 2022-10-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_purchase_purchase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='fee',
        ),
    ]
