# Generated by Django 4.0.5 on 2022-10-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_purchase_email_purchase_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_method',
            field=models.CharField(default='In the store', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='street_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseAddress',
        ),
    ]
