# Generated by Django 4.0.5 on 2022-10-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_purchase_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
    ]
